export enum ERROR_CODES {
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN",
  MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}
